# -*- mode: ruby -*-

# vi: set ft=ruby :



# All Vagrant configuration is done below.

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.box_version = "20211001.0.0"

    config.vm.network "private_network", ip: "192.168.11.22"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox"

    config.vm.provision "shell", inline: <<-SHELL

    sudo apt update
sudo apt install apache2
sudo systemctl stop apache2.service
sudo systemctl start apache2.service
sudo systemctl enable apache2.service
sudo apt install mariadb-server mariadb-client
sudo systemctl stop mariadb.service
sudo systemctl start mariadb.service
sudo systemctl enable mariadb.service
sudo mysql_secure_installation

sudo mysql -u root -p
#Install PHP 7.4
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install php7.4 libapache2-mod-php7.4 php7.4-common php7.4-curl php7.4-mbstring php7.4-xmlrpc php7.4-mysql php7.4-gd php7.4-xml php7.4-cli php7.4-zip

sudo mysql -u root -p
CREATE DATABASE ampache;
CREATE USER 'ampacheuser'@'localhost' IDENTIFIED BY '1234';
GRANT ALL ON ampache.* TO 'ampacheuser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT;
#Install Ampache
cd /tmp
wget https://github.com/ampache/ampache/releases/download/4.1.1/ampache-4.1.1_all.zip
sudo unzip ampache-4.1.1_all.zip -d /var/www/ampache
sudo chown -R www-data:www-data /var/www/ampache/
sudo chmod -R 755 /var/www/ampache/
#sudo nano /etc/apache2/sites-available/ampache.conf
#<VirtualHost *:80>
#     ServerAdmin admin@example.com
#     DocumentRoot /var/www/ampache
#     ServerName example.com
#     ServerAlias www.example.com
#
#     <Directory /var/www/glpi/>
#        Options +FollowSymlinks
#        AllowOverride All
#        Require all granted
#     </Directory>
#
#     ErrorLog ${APACHE_LOG_DIR}/error.log
#     CustomLog ${APACHE_LOG_DIR}/access.log combined
#
#</VirtualHost>

sudo a2ensite ampache.conf
sudo a2enmod rewrite
sudo systemctl restart apache2.service

  

SHELL

end


