
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "v20211001.0.0"
  config.vm.provider = "Virtualbox"
  config.vm.provision = "shell", inline <<-SHELL
  sudo yum -y install httpd php php-pdo mysql-server php-mysql yasm wget

	sudo chkconfig httpd on
	sudo service httpd start
	
	sudo chkconfig mysqld on
	sudo service mysqld start

#	GRANT ALL PRIVILEGES ON ampache.* TO ampache@localhost IDENTIFIED BY 'ampache' WITH GRANT OPTION;

	git clone git://source.ffmpeg.org/ffmpeg.git ffmpeg
	cd ffmpeg
	sh configure
	sudo make install

	cd
	wget https://github.com/ampache/ampache/archive/master.tar.gz
	tar xvfz master.tar.gz
	sudo mv ampache-master /var/www/html/
	cd /var/www/html/ampache-master
	sudo chmod a+w config
	sudo chmod a+w rest
	sudo chmod a+w play

	# http://localhost/ampache-master/

# for ampache

end
